<?php
$data = array (
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '活动报名',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '80',
    'name' => '活动报名',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '围棋',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '83',
    'name' => '围棋',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '象棋',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '81',
    'name' => '象棋',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '国际象棋',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => '国际象棋',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '其他活动',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '93',
    'name' => '其他活动',
  ),
);
?>